INSERT INTO  perimeters.cerema_aom_2020(id_reseau, nom_reseau, siren_aom, nom_aom, forme_juridique_aom, region, departement, siren_group,
  lien_banatic, nom_group, forme_juridique_group, nb_membres, pop_aom_2017, siren_membre, com, nom_membre, pop_com_2017, pop_banatic_2017,
  surface, nom_com, wikipedia)
SELECT * FROM
json_to_recordset($1) 
as temp("Id réseau" integer,
 "Nom du réseau" varchar,
  "N° SIREN AOM" integer,
  "Nom de l’AOM" varchar,
  "Forme juridique de l’AOM" varchar,
  "Région siège" varchar,
  "Département siège" varchar,
  "N° SIREN groupement" integer,
  "Lien Banatic" varchar,
  "Nom du groupement" varchar,
  "Nature juridique du groupement" varchar,
  "Nombre de membres" integer,
  "Population  totale 2017 (Banatic)" integer,
  "Siren membre" integer,
  "N° INSEE" varchar,
  "Nom membre" varchar,
  "Population  municipale 2017" varchar,
  "Population  totale 2017 (Banatic)_1"integer,
  "Surface (km²)" integer,
  "intitulé commune wikipédia" varchar,
  "Lien Page wikipedia" varchar);