name: 'Deploy demo'

on:
  push:
    branches: [main]


defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Prepare keys 
        run: |
          mkdir -p ~/.ssh
          echo -e "$KEY" > ~/.ssh/id_rsa
          chmod og-rwx ~/.ssh/id_rsa
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: ssh $USER@$HOST $COMMAND
        env: 
         HOST: ${{ secrets.REMOTE_HOST }}
         USER: ${{ secrets.REMOTE_USER }}
         COMMAND: >
           export PUBLIC_DIR=/home/node/public &&
           cd /home/node/app &&
           sudo -u node git pull &&
           sh install.sh &&
           sudo systemctl restart app.service
 