name: 'Test'

on:
  pull_request:
    branches: [main]


defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build api and frontend
        run: sh install.sh
